### ISSUE TITLE
flake8-return does not recognize `assert False` as an implicit return.

### ISSUE THREAD

**Issue by kdeberk** [Afonasev/flake8-return#2]
* Date you used flake8-return: today
* flake8-return version used, if any: 0.3.1
* Python version, if any: Python 3.7.2
* Operating System: Linux

### Description

We sometimes end a method with `assert False, "some reason"` as a sanity check. The current version of flake8-return sees this as a violation of R503.

```
def some_method(parameter):
   if some_test:
     return some_value
   elif another_test:
     return another_value
   else:
     assert False, "parameter was not some_value nor another_value"
```
This `assert False` is equivalent to `raise AssertionError` which flake8-return does recognize. We would like to see flake8-return treat both statements as equivalent.

**Comment by Afonasev** [comment]
Thx for issue. I will fix it soon.

**Comment by Afonasev** [comment]
done!
